package jp.co.ccube.ss.entity;

public class CaseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.project_id
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case.case_id
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    private Integer caseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.project_id
     *
     * @return the value of case.project_id
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.project_id
     *
     * @param projectId the value for case.project_id
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case.case_id
     *
     * @return the value of case.case_id
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case.case_id
     *
     * @param caseId the value for case.case_id
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }
}