package jp.co.ccube.ss.entity;

public class CaseProject extends Case{



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    private String projectName;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }



}
