package jp.co.ccube.ss.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Charge extends ChargeKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column charge.employee_no
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	private Integer employeeNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column charge.client_id
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	private Integer clientId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column charge.engineer_name
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	private String engineerName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column charge.price
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	private Integer price;

	private Integer excessAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column charge.start_date
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	private Date startDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column charge.end_date
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	private Date endDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column charge.man_hours
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	private BigDecimal manHours;

	private Date deletedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column charge.employee_no
	 *
	 * @return the value of charge.employee_no
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public Integer getEmployeeNo() {
		return employeeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column charge.employee_no
	 *
	 * @param employeeNo the value for charge.employee_no
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public void setEmployeeNo(Integer employeeNo) {
		this.employeeNo = employeeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column charge.client_id
	 *
	 * @return the value of charge.client_id
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public Integer getClientId() {
		return clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column charge.client_id
	 *
	 * @param clientId the value for charge.client_id
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column charge.engineer_name
	 *
	 * @return the value of charge.engineer_name
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public String getEngineerName() {
		return engineerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column charge.engineer_name
	 *
	 * @param engineerName the value for charge.engineer_name
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public void setEngineerName(String engineerName) {
		this.engineerName = engineerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column charge.price
	 *
	 * @return the value of charge.price
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column charge.price
	 *
	 * @param price the value for charge.price
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	public Integer getExcessAmount() {
		return excessAmount;
	}

	public void setExcessAmount(Integer excessAmount) {
		this.excessAmount = excessAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column charge.start_date
	 *
	 * @return the value of charge.start_date
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column charge.start_date
	 *
	 * @param startDate the value for charge.start_date
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column charge.end_date
	 *
	 * @return the value of charge.end_date
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column charge.end_date
	 *
	 * @param endDate the value for charge.end_date
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column charge.man_hours
	 *
	 * @return the value of charge.man_hours
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public BigDecimal getManHours() {
		return manHours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column charge.man_hours
	 *
	 * @param manHours the value for charge.man_hours
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	public void setManHours(BigDecimal manHours) {
		this.manHours = manHours;
	}
}