package jp.co.ccube.ss.entity;

public class ChargeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.project_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.case_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge.branch_no
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Integer branchNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.project_id
     *
     * @return the value of charge.project_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.project_id
     *
     * @param projectId the value for charge.project_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.case_id
     *
     * @return the value of charge.case_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.case_id
     *
     * @param caseId the value for charge.case_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge.branch_no
     *
     * @return the value of charge.branch_no
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Integer getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge.branch_no
     *
     * @param branchNo the value for charge.branch_no
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setBranchNo(Integer branchNo) {
        this.branchNo = branchNo;
    }
}