package jp.co.ccube.ss.entity;

public class ClientResponsible extends ClientResponsibleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.department
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.position
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.name
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.kana
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private String kana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.address
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.telephone
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.mail_address
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private String mailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.description
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.department
     *
     * @return the value of client_responsible.department
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.department
     *
     * @param department the value for client_responsible.department
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.position
     *
     * @return the value of client_responsible.position
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.position
     *
     * @param position the value for client_responsible.position
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.name
     *
     * @return the value of client_responsible.name
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.name
     *
     * @param name the value for client_responsible.name
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.kana
     *
     * @return the value of client_responsible.kana
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public String getKana() {
        return kana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.kana
     *
     * @param kana the value for client_responsible.kana
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setKana(String kana) {
        this.kana = kana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.address
     *
     * @return the value of client_responsible.address
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.address
     *
     * @param address the value for client_responsible.address
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.telephone
     *
     * @return the value of client_responsible.telephone
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.telephone
     *
     * @param telephone the value for client_responsible.telephone
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.mail_address
     *
     * @return the value of client_responsible.mail_address
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.mail_address
     *
     * @param mailAddress the value for client_responsible.mail_address
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.description
     *
     * @return the value of client_responsible.description
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.description
     *
     * @param description the value for client_responsible.description
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}