package jp.co.ccube.ss.entity;

public class Client {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.company_id
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.company_name
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.address
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.telephone
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.mail_address
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    private String mailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.type
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.description
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.company_id
     *
     * @return the value of client.company_id
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.company_id
     *
     * @param companyId the value for client.company_id
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.company_name
     *
     * @return the value of client.company_name
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.company_name
     *
     * @param companyName the value for client.company_name
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.address
     *
     * @return the value of client.address
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.address
     *
     * @param address the value for client.address
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.telephone
     *
     * @return the value of client.telephone
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.telephone
     *
     * @param telephone the value for client.telephone
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.mail_address
     *
     * @return the value of client.mail_address
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.mail_address
     *
     * @param mailAddress the value for client.mail_address
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.type
     *
     * @return the value of client.type
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.type
     *
     * @param type the value for client.type
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.description
     *
     * @return the value of client.description
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.description
     *
     * @param description the value for client.description
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}