package jp.co.ccube.ss.entity;

public class ClientResponsibleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.company_id
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_responsible.branch_no
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    private Integer branchNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.company_id
     *
     * @return the value of client_responsible.company_id
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.company_id
     *
     * @param companyId the value for client_responsible.company_id
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_responsible.branch_no
     *
     * @return the value of client_responsible.branch_no
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public Integer getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_responsible.branch_no
     *
     * @param branchNo the value for client_responsible.branch_no
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    public void setBranchNo(Integer branchNo) {
        this.branchNo = branchNo;
    }
}