package jp.co.ccube.ss.entity;

import java.util.Date;

public class Dispatch extends DispatchKey {

	private String startYear;
	private String startMonth;
	private String startDay;
	private String endYear;
	private String endMonth;
	private String endDay;
	private Integer lowerTimem;
	private Integer upperTImem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatch.start_date
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatch.end_date
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatch.lower_time
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    private Integer lowerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatch.upper_time
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    private Integer upperTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatch.production
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    private String production;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatch.start_date
     *
     * @return the value of dispatch.start_date
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatch.start_date
     *
     * @param startDate the value for dispatch.start_date
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatch.end_date
     *
     * @return the value of dispatch.end_date
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatch.end_date
     *
     * @param endDate the value for dispatch.end_date
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatch.lower_time
     *
     * @return the value of dispatch.lower_time
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public Integer getLowerTime() {
        return lowerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatch.lower_time
     *
     * @param lowerTime the value for dispatch.lower_time
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public void setLowerTime(Integer lowerTime) {
        this.lowerTime = lowerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatch.upper_time
     *
     * @return the value of dispatch.upper_time
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public Integer getUpperTime() {
        return upperTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatch.upper_time
     *
     * @param upperTime the value for dispatch.upper_time
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public void setUpperTime(Integer upperTime) {
        this.upperTime = upperTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatch.production
     *
     * @return the value of dispatch.production
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public String getProduction() {
        return production;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatch.production
     *
     * @param production the value for dispatch.production
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public void setProduction(String production) {
        this.production = production;
    }

	public String getStartYear() {
		return startYear;
	}

	public void setStartYear(String startYear) {
		this.startYear = startYear;
	}

	public String getStartMonth() {
		return startMonth;
	}

	public void setStartMonth(String startMonth) {
		this.startMonth = startMonth;
	}

	public String getStartDay() {
		return startDay;
	}

	public void setStartDay(String startDay) {
		this.startDay = startDay;
	}

	public String getEndYear() {
		return endYear;
	}

	public void setEndYear(String endYear) {
		this.endYear = endYear;
	}

	public String getEndMonth() {
		return endMonth;
	}

	public void setEndMonth(String endMonth) {
		this.endMonth = endMonth;
	}

	public String getEndDay() {
		return endDay;
	}

	public void setEndDay(String endDay) {
		this.endDay = endDay;
	}

	public Integer getLowerTimem() {
		return lowerTimem;
	}

	public void setLowerTimem(Integer lowerTimem) {
		this.lowerTimem = lowerTimem;
	}

	public Integer getUpperTImem() {
		return upperTImem;
	}

	public void setUpperTImem(Integer upperTImem) {
		this.upperTImem = upperTImem;
	}
}