package jp.co.ccube.ss.entity;

public class DispatchKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatch.project_id
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatch.case_id
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    private Integer caseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatch.project_id
     *
     * @return the value of dispatch.project_id
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatch.project_id
     *
     * @param projectId the value for dispatch.project_id
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatch.case_id
     *
     * @return the value of dispatch.case_id
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatch.case_id
     *
     * @param caseId the value for dispatch.case_id
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }
}