package jp.co.ccube.ss.entity;

import java.util.Date;

public class Employee {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_no
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	private Integer employeeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.department
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.position
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.name
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.telephon
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	private String telephon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.mail_address
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	private String mailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.cost
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	private Integer cost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.role
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	private Integer role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.delete_at
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	private Date deleteAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_no
	 * @return  the value of employee.employee_no
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public Integer getEmployeeNo() {
		return employeeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_no
	 * @param employeeNo  the value for employee.employee_no
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public void setEmployeeNo(Integer employeeNo) {
		this.employeeNo = employeeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.department
	 * @return  the value of employee.department
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.department
	 * @param department  the value for employee.department
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.position
	 * @return  the value of employee.position
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.position
	 * @param position  the value for employee.position
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.name
	 * @return  the value of employee.name
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.name
	 * @param name  the value for employee.name
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.telephon
	 * @return  the value of employee.telephon
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public String getTelephon() {
		return telephon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.telephon
	 * @param telephon  the value for employee.telephon
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public void setTelephon(String telephon) {
		this.telephon = telephon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.mail_address
	 * @return  the value of employee.mail_address
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public String getMailAddress() {
		return mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.mail_address
	 * @param mailAddress  the value for employee.mail_address
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.cost
	 * @return  the value of employee.cost
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public Integer getCost() {
		return cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.cost
	 * @param cost  the value for employee.cost
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public void setCost(Integer cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.role
	 * @return  the value of employee.role
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.role
	 * @param role  the value for employee.role
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.delete_at
	 * @return  the value of employee.delete_at
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public Date getDeleteAt() {
		return deleteAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.delete_at
	 * @param deleteAt  the value for employee.delete_at
	 * @mbggenerated  Fri May 25 10:36:37 JST 2018
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}

}
