package jp.co.ccube.ss.entity;

public class EngineerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.project_id
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.case_id
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.branch_no
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer branchNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.project_id
     *
     * @return the value of engineer.project_id
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.project_id
     *
     * @param projectId the value for engineer.project_id
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.case_id
     *
     * @return the value of engineer.case_id
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.case_id
     *
     * @param caseId the value for engineer.case_id
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.branch_no
     *
     * @return the value of engineer.branch_no
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.branch_no
     *
     * @param branchNo the value for engineer.branch_no
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setBranchNo(Integer branchNo) {
        this.branchNo = branchNo;
    }
}