package jp.co.ccube.ss.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Engineer extends EngineerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.employee_no
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer employeeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.client_id
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.engineer_name
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private String engineerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.price
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.excess_price
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer excessPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.deduction_price
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer deductionPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.cost
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.excess_cost
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer excessCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.deduction_cost
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Integer deductionCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.start_date
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.end_date
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.man_hours
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    private BigDecimal manHours;

    public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	private String companyName;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.employee_no
     *
     * @return the value of engineer.employee_no
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getEmployeeNo() {
        return employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.employee_no
     *
     * @param employeeNo the value for engineer.employee_no
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setEmployeeNo(Integer employeeNo) {
        this.employeeNo = employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.client_id
     *
     * @return the value of engineer.client_id
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.client_id
     *
     * @param clientId the value for engineer.client_id
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.engineer_name
     *
     * @return the value of engineer.engineer_name
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public String getEngineerName() {
        return engineerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.engineer_name
     *
     * @param engineerName the value for engineer.engineer_name
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setEngineerName(String engineerName) {
        this.engineerName = engineerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.price
     *
     * @return the value of engineer.price
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.price
     *
     * @param price the value for engineer.price
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.excess_price
     *
     * @return the value of engineer.excess_price
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getExcessPrice() {
        return excessPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.excess_price
     *
     * @param excessPrice the value for engineer.excess_price
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setExcessPrice(Integer excessPrice) {
        this.excessPrice = excessPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.deduction_price
     *
     * @return the value of engineer.deduction_price
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getDeductionPrice() {
        return deductionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.deduction_price
     *
     * @param deductionPrice the value for engineer.deduction_price
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setDeductionPrice(Integer deductionPrice) {
        this.deductionPrice = deductionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.cost
     *
     * @return the value of engineer.cost
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.cost
     *
     * @param cost the value for engineer.cost
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.excess_cost
     *
     * @return the value of engineer.excess_cost
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getExcessCost() {
        return excessCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.excess_cost
     *
     * @param excessCost the value for engineer.excess_cost
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setExcessCost(Integer excessCost) {
        this.excessCost = excessCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.deduction_cost
     *
     * @return the value of engineer.deduction_cost
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Integer getDeductionCost() {
        return deductionCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.deduction_cost
     *
     * @param deductionCost the value for engineer.deduction_cost
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setDeductionCost(Integer deductionCost) {
        this.deductionCost = deductionCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.start_date
     *
     * @return the value of engineer.start_date
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.start_date
     *
     * @param startDate the value for engineer.start_date
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.end_date
     *
     * @return the value of engineer.end_date
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.end_date
     *
     * @param endDate the value for engineer.end_date
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.man_hours
     *
     * @return the value of engineer.man_hours
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public BigDecimal getManHours() {
        return manHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.man_hours
     *
     * @param manHours the value for engineer.man_hours
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    public void setManHours(BigDecimal manHours) {
        this.manHours = manHours;
    }
}