package jp.co.ccube.ss.entity;

public class EntrustedKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrusted.project_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrusted.case_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Integer caseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrusted.project_id
     *
     * @return the value of entrusted.project_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrusted.project_id
     *
     * @param projectId the value for entrusted.project_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrusted.case_id
     *
     * @return the value of entrusted.case_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrusted.case_id
     *
     * @param caseId the value for entrusted.case_id
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }
}