package jp.co.ccube.ss.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Entrusted extends EntrustedKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrusted.start_date
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrusted.end_date
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrusted.man_hour
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private BigDecimal manHour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrusted.price
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrusted.additional
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Integer additional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrusted.sales
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    private Integer sales;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrusted.start_date
     *
     * @return the value of entrusted.start_date
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrusted.start_date
     *
     * @param startDate the value for entrusted.start_date
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrusted.end_date
     *
     * @return the value of entrusted.end_date
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrusted.end_date
     *
     * @param endDate the value for entrusted.end_date
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrusted.man_hour
     *
     * @return the value of entrusted.man_hour
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public BigDecimal getManHour() {
        return manHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrusted.man_hour
     *
     * @param manHour the value for entrusted.man_hour
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setManHour(BigDecimal manHour) {
        this.manHour = manHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrusted.price
     *
     * @return the value of entrusted.price
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrusted.price
     *
     * @param price the value for entrusted.price
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrusted.additional
     *
     * @return the value of entrusted.additional
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Integer getAdditional() {
        return additional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrusted.additional
     *
     * @param additional the value for entrusted.additional
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setAdditional(Integer additional) {
        this.additional = additional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrusted.sales
     *
     * @return the value of entrusted.sales
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrusted.sales
     *
     * @param sales the value for entrusted.sales
     *
     * @mbggenerated Thu Jul 26 11:44:04 JST 2018
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }
}