package jp.co.ccube.ss.entity;

public class MClassificationKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column m_classification.classification_code
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	private String classificationCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column m_classification.classification_id
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	private Integer classificationId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column m_classification.classification_code
	 *
	 * @return the value of m_classification.classification_code
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	public String getClassificationCode() {
		return classificationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column m_classification.classification_code
	 *
	 * @param classificationCode the value for
	 *            m_classification.classification_code
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	public void setClassificationCode(String classificationCode) {
		this.classificationCode = classificationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column m_classification.classification_id
	 *
	 * @return the value of m_classification.classification_id
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	public Integer getClassificationId() {
		return classificationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column m_classification.classification_id
	 *
	 * @param classificationId the value for m_classification.classification_id
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	public void setClassificationId(Integer classificationId) {
		this.classificationId = classificationId;
	}
}