package jp.co.ccube.ss.entity;

public class MClassification extends MClassificationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_classification.classification_name
     *
     * @mbggenerated Wed Aug 22 16:52:44 JST 2018
     */
    private String classificationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_classification.classification_name
     *
     * @return the value of m_classification.classification_name
     *
     * @mbggenerated Wed Aug 22 16:52:44 JST 2018
     */
    public String getClassificationName() {
        return classificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_classification.classification_name
     *
     * @param classificationName the value for m_classification.classification_name
     *
     * @mbggenerated Wed Aug 22 16:52:44 JST 2018
     */
    public void setClassificationName(String classificationName) {
        this.classificationName = classificationName;
    }
}