package jp.co.ccube.ss.entity;

import java.util.Date;

public class Session {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.jsessionid
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    private String jsessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.account_id
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.created_at
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.jsessionid
     *
     * @return the value of session.jsessionid
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    public String getJsessionid() {
        return jsessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.jsessionid
     *
     * @param jsessionid the value for session.jsessionid
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    public void setJsessionid(String jsessionid) {
        this.jsessionid = jsessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.account_id
     *
     * @return the value of session.account_id
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.account_id
     *
     * @param accountId the value for session.account_id
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.created_at
     *
     * @return the value of session.created_at
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.created_at
     *
     * @param createdAt the value for session.created_at
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}