package jp.co.ccube.ss.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UsersExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public UsersExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andAccountIdIsNull() {
			addCriterion("account_id is null");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNotNull() {
			addCriterion("account_id is not null");
			return (Criteria) this;
		}

		public Criteria andAccountIdEqualTo(String value) {
			addCriterion("account_id =", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotEqualTo(String value) {
			addCriterion("account_id <>", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThan(String value) {
			addCriterion("account_id >", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
			addCriterion("account_id >=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThan(String value) {
			addCriterion("account_id <", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThanOrEqualTo(String value) {
			addCriterion("account_id <=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLike(String value) {
			addCriterion("account_id like", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotLike(String value) {
			addCriterion("account_id not like", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIn(List<String> values) {
			addCriterion("account_id in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotIn(List<String> values) {
			addCriterion("account_id not in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdBetween(String value1, String value2) {
			addCriterion("account_id between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotBetween(String value1, String value2) {
			addCriterion("account_id not between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andDepartmentIsNull() {
			addCriterion("department is null");
			return (Criteria) this;
		}

		public Criteria andDepartmentIsNotNull() {
			addCriterion("department is not null");
			return (Criteria) this;
		}

		public Criteria andDepartmentEqualTo(String value) {
			addCriterion("department =", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotEqualTo(String value) {
			addCriterion("department <>", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentGreaterThan(String value) {
			addCriterion("department >", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
			addCriterion("department >=", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentLessThan(String value) {
			addCriterion("department <", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentLessThanOrEqualTo(String value) {
			addCriterion("department <=", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentLike(String value) {
			addCriterion("department like", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotLike(String value) {
			addCriterion("department not like", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentIn(List<String> values) {
			addCriterion("department in", values, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotIn(List<String> values) {
			addCriterion("department not in", values, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentBetween(String value1, String value2) {
			addCriterion("department between", value1, value2, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotBetween(String value1, String value2) {
			addCriterion("department not between", value1, value2, "department");
			return (Criteria) this;
		}

		public Criteria andPositionIsNull() {
			addCriterion("position is null");
			return (Criteria) this;
		}

		public Criteria andPositionIsNotNull() {
			addCriterion("position is not null");
			return (Criteria) this;
		}

		public Criteria andPositionEqualTo(String value) {
			addCriterion("position =", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotEqualTo(String value) {
			addCriterion("position <>", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThan(String value) {
			addCriterion("position >", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThanOrEqualTo(String value) {
			addCriterion("position >=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThan(String value) {
			addCriterion("position <", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThanOrEqualTo(String value) {
			addCriterion("position <=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLike(String value) {
			addCriterion("position like", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotLike(String value) {
			addCriterion("position not like", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionIn(List<String> values) {
			addCriterion("position in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotIn(List<String> values) {
			addCriterion("position not in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionBetween(String value1, String value2) {
			addCriterion("position between", value1, value2, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotBetween(String value1, String value2) {
			addCriterion("position not between", value1, value2, "position");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNull() {
			addCriterion("telephone is null");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNotNull() {
			addCriterion("telephone is not null");
			return (Criteria) this;
		}

		public Criteria andTelephoneEqualTo(String value) {
			addCriterion("telephone =", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotEqualTo(String value) {
			addCriterion("telephone <>", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThan(String value) {
			addCriterion("telephone >", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
			addCriterion("telephone >=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThan(String value) {
			addCriterion("telephone <", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThanOrEqualTo(String value) {
			addCriterion("telephone <=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLike(String value) {
			addCriterion("telephone like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotLike(String value) {
			addCriterion("telephone not like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneIn(List<String> values) {
			addCriterion("telephone in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotIn(List<String> values) {
			addCriterion("telephone not in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneBetween(String value1, String value2) {
			addCriterion("telephone between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotBetween(String value1, String value2) {
			addCriterion("telephone not between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andMailAddressIsNull() {
			addCriterion("mail_address is null");
			return (Criteria) this;
		}

		public Criteria andMailAddressIsNotNull() {
			addCriterion("mail_address is not null");
			return (Criteria) this;
		}

		public Criteria andMailAddressEqualTo(String value) {
			addCriterion("mail_address =", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotEqualTo(String value) {
			addCriterion("mail_address <>", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressGreaterThan(String value) {
			addCriterion("mail_address >", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressGreaterThanOrEqualTo(String value) {
			addCriterion("mail_address >=", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLessThan(String value) {
			addCriterion("mail_address <", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLessThanOrEqualTo(String value) {
			addCriterion("mail_address <=", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLike(String value) {
			addCriterion("mail_address like", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotLike(String value) {
			addCriterion("mail_address not like", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressIn(List<String> values) {
			addCriterion("mail_address in", values, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotIn(List<String> values) {
			addCriterion("mail_address not in", values, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressBetween(String value1, String value2) {
			addCriterion("mail_address between", value1, value2, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotBetween(String value1, String value2) {
			addCriterion("mail_address not between", value1, value2, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitIsNull() {
			addCriterion("password_limit is null");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitIsNotNull() {
			addCriterion("password_limit is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitEqualTo(Date value) {
			addCriterionForJDBCDate("password_limit =", value, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitNotEqualTo(Date value) {
			addCriterionForJDBCDate("password_limit <>", value, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitGreaterThan(Date value) {
			addCriterionForJDBCDate("password_limit >", value, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("password_limit >=", value, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitLessThan(Date value) {
			addCriterionForJDBCDate("password_limit <", value, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("password_limit <=", value, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitIn(List<Date> values) {
			addCriterionForJDBCDate("password_limit in", values, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitNotIn(List<Date> values) {
			addCriterionForJDBCDate("password_limit not in", values, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("password_limit between", value1, value2, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPasswordLimitNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("password_limit not between", value1, value2, "passwordLimit");
			return (Criteria) this;
		}

		public Criteria andPermissionIsNull() {
			addCriterion("permission is null");
			return (Criteria) this;
		}

		public Criteria andPermissionIsNotNull() {
			addCriterion("permission is not null");
			return (Criteria) this;
		}

		public Criteria andPermissionEqualTo(Integer value) {
			addCriterion("permission =", value, "permission");
			return (Criteria) this;
		}

		public Criteria andPermissionNotEqualTo(Integer value) {
			addCriterion("permission <>", value, "permission");
			return (Criteria) this;
		}

		public Criteria andPermissionGreaterThan(Integer value) {
			addCriterion("permission >", value, "permission");
			return (Criteria) this;
		}

		public Criteria andPermissionGreaterThanOrEqualTo(Integer value) {
			addCriterion("permission >=", value, "permission");
			return (Criteria) this;
		}

		public Criteria andPermissionLessThan(Integer value) {
			addCriterion("permission <", value, "permission");
			return (Criteria) this;
		}

		public Criteria andPermissionLessThanOrEqualTo(Integer value) {
			addCriterion("permission <=", value, "permission");
			return (Criteria) this;
		}

		public Criteria andPermissionIn(List<Integer> values) {
			addCriterion("permission in", values, "permission");
			return (Criteria) this;
		}

		public Criteria andPermissionNotIn(List<Integer> values) {
			addCriterion("permission not in", values, "permission");
			return (Criteria) this;
		}

		public Criteria andPermissionBetween(Integer value1, Integer value2) {
			addCriterion("permission between", value1, value2, "permission");
			return (Criteria) this;
		}

		public Criteria andPermissionNotBetween(Integer value1, Integer value2) {
			addCriterion("permission not between", value1, value2, "permission");
			return (Criteria) this;
		}

		public Criteria andDeletedAtIsNull() {
			addCriterion("deleted_at is null");
			return (Criteria) this;
		}

		public Criteria andDeletedAtIsNotNull() {
			addCriterion("deleted_at is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedAtEqualTo(Date value) {
			addCriterion("deleted_at =", value, "deletedAt");
			return (Criteria) this;
		}

		public Criteria andDeletedAtNotEqualTo(Date value) {
			addCriterion("deleted_at <>", value, "deletedAt");
			return (Criteria) this;
		}

		public Criteria andDeletedAtGreaterThan(Date value) {
			addCriterion("deleted_at >", value, "deletedAt");
			return (Criteria) this;
		}

		public Criteria andDeletedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("deleted_at >=", value, "deletedAt");
			return (Criteria) this;
		}

		public Criteria andDeletedAtLessThan(Date value) {
			addCriterion("deleted_at <", value, "deletedAt");
			return (Criteria) this;
		}

		public Criteria andDeletedAtLessThanOrEqualTo(Date value) {
			addCriterion("deleted_at <=", value, "deletedAt");
			return (Criteria) this;
		}

		public Criteria andDeletedAtIn(List<Date> values) {
			addCriterion("deleted_at in", values, "deletedAt");
			return (Criteria) this;
		}

		public Criteria andDeletedAtNotIn(List<Date> values) {
			addCriterion("deleted_at not in", values, "deletedAt");
			return (Criteria) this;
		}

		public Criteria andDeletedAtBetween(Date value1, Date value2) {
			addCriterion("deleted_at between", value1, value2, "deletedAt");
			return (Criteria) this;
		}

		public Criteria andDeletedAtNotBetween(Date value1, Date value2) {
			addCriterion("deleted_at not between", value1, value2, "deletedAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table users
	 *
	 * @mbggenerated do_not_delete_during_merge Wed May 02 10:57:00 JST 2018
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}
}