package jp.co.ccube.ss.entity;

import java.util.Date;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.account_id
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private String accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.department
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private String department;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.position
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.name
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.telephone
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.mail_address
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private String mailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password_limit
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private Date passwordLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.permission
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private Integer permission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.deleted_at
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	private Date deletedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.account_id
	 * @return  the value of users.account_id
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.account_id
	 * @param accountId  the value for users.account_id
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.department
	 * @return  the value of users.department
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.department
	 * @param department  the value for users.department
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.position
	 * @return  the value of users.position
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.position
	 * @param position  the value for users.position
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.name
	 * @return  the value of users.name
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.name
	 * @param name  the value for users.name
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.telephone
	 * @return  the value of users.telephone
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.telephone
	 * @param telephone  the value for users.telephone
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.mail_address
	 * @return  the value of users.mail_address
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public String getMailAddress() {
		return mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.mail_address
	 * @param mailAddress  the value for users.mail_address
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
	 * @return  the value of users.password
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
	 * @param password  the value for users.password
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password_limit
	 * @return  the value of users.password_limit
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public Date getPasswordLimit() {
		return passwordLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password_limit
	 * @param passwordLimit  the value for users.password_limit
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setPasswordLimit(Date passwordLimit) {
		this.passwordLimit = passwordLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.permission
	 * @return  the value of users.permission
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public Integer getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.permission
	 * @param permission  the value for users.permission
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setPermission(Integer permission) {
		this.permission = permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.deleted_at
	 * @return  the value of users.deleted_at
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public Date getDeletedAt() {
		return deletedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.deleted_at
	 * @param deletedAt  the value for users.deleted_at
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}
}