package jp.co.ccube.ss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.co.ccube.ss.entity.Case;
import jp.co.ccube.ss.entity.CaseDetail;
import jp.co.ccube.ss.entity.CaseExample;
import jp.co.ccube.ss.entity.CaseKey;
import jp.co.ccube.ss.entity.CaseProject;


@Mapper
public interface CaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    int countByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    int deleteByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    int deleteByPrimaryKey(CaseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    int insert(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    int insertSelective(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    List<Case> selectByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    Case selectByPrimaryKey(CaseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    int updateByExampleSelective(@Param("record") Case record, @Param("example") CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    int updateByExample(@Param("record") Case record, @Param("example") CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    int updateByPrimaryKeySelective(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case
     *
     * @mbggenerated Thu Jul 26 11:02:32 JST 2018
     */
    int updateByPrimaryKey(Case record);

	List<CaseProject> selectByCase(CaseProject record);
	List<CaseDetail> selectByDetail(CaseDetail record);

	CaseDetail selectByEditSearch(CaseDetail record);

	void deletedAtUpdate(Integer id);



}