package jp.co.ccube.ss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import jp.co.ccube.ss.entity.Charge;
import jp.co.ccube.ss.entity.ChargeExample;

public interface ChargeDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	int countByExample(ChargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	int deleteByExample(ChargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	int deleteByPrimaryKey(Integer key, Integer er, Integer y);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	int insert(Charge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	int insertSelective(Charge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	List<Charge> selectByExample(ChargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	Charge selectByPrimaryKey(Integer key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	int updateByExampleSelective(@Param("record") Charge record, @Param("example") ChargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	int updateByExample(@Param("record") Charge record, @Param("example") ChargeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	int updateByPrimaryKeySelective(Charge record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table charge
	 *
	 * @mbggenerated Thu Jul 26 11:44:04 JST 2018
	 */
	int updateByPrimaryKey(Charge record);

	void deletedAtUpdate(Integer accountId, Integer caseId, Integer BranchNo);
}