package jp.co.ccube.ss.dao;

import java.util.List;
import jp.co.ccube.ss.entity.Client;
import jp.co.ccube.ss.entity.ClientExample;
import org.apache.ibatis.annotations.Param;

public interface ClientDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    int countByExample(ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    int deleteByExample(ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    int insertSelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    List<Client> selectByExample(ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    Client selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    int updateByExampleSelective(@Param("record") Client record, @Param("example") ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    int updateByExample(@Param("record") Client record, @Param("example") ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    int updateByPrimaryKeySelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Jun 04 11:52:17 JST 2018
     */
    int updateByPrimaryKey(Client record);
}