package jp.co.ccube.ss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import jp.co.ccube.ss.entity.ClientResponsible;
import jp.co.ccube.ss.entity.ClientResponsibleExample;
import jp.co.ccube.ss.entity.ClientResponsibleKey;

public interface ClientResponsibleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    int countByExample(ClientResponsibleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    int deleteByExample(ClientResponsibleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    int deleteByPrimaryKey(ClientResponsibleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    int insert(ClientResponsible record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    int insertSelective(ClientResponsible record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    List<ClientResponsible> selectByExample(ClientResponsibleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    ClientResponsible selectByPrimaryKey(ClientResponsibleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    int updateByExampleSelective(@Param("record") ClientResponsible record, @Param("example") ClientResponsibleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    int updateByExample(@Param("record") ClientResponsible record, @Param("example") ClientResponsibleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    int updateByPrimaryKeySelective(ClientResponsible record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_responsible
     *
     * @mbggenerated Wed Aug 29 13:48:17 JST 2018
     */
    int updateByPrimaryKey(ClientResponsible record);

    List<ClientResponsible> selectByClientR(ClientResponsible record);
}