package jp.co.ccube.ss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.co.ccube.ss.entity.Dispatch;
import jp.co.ccube.ss.entity.DispatchExample;
import jp.co.ccube.ss.entity.DispatchKey;

@Mapper
public interface DispatchDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    int countByExample(DispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    int deleteByExample(DispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    int deleteByPrimaryKey(DispatchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    int insert(Dispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    int insertSelective(Dispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    List<Dispatch> selectByExample(DispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    Dispatch selectByPrimaryKey(Dispatch key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    int updateByExampleSelective(@Param("record") Dispatch record, @Param("example") DispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    int updateByExample(@Param("record") Dispatch record, @Param("example") DispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    int updateByPrimaryKeySelective(Dispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbggenerated Tue Jul 31 11:05:33 JST 2018
     */
    int updateByPrimaryKey(Dispatch record);

    int selectdispatch(Dispatch record);
}

