package jp.co.ccube.ss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import jp.co.ccube.ss.entity.Client;
import jp.co.ccube.ss.entity.Engineer;
import jp.co.ccube.ss.entity.EngineerExample;

public interface EngineerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    int countByExample(EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    int deleteByExample(EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    int deleteByPrimaryKey(Integer key,Integer ey,Integer y);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    int insert(Engineer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    int insertSelective(Engineer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    List<Engineer> selectByExample(EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    Engineer selectByPrimaryKey(Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    int updateByExampleSelective(@Param("record") Engineer record, @Param("example") EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    int updateByExample(@Param("record") Engineer record, @Param("example") EngineerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    int updateByPrimaryKeySelective(Engineer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbggenerated Tue Jul 31 09:26:06 JST 2018
     */
    int updateByPrimaryKey(Engineer record);


    Engineer select(Engineer key);
Engineer employeeSelect(Engineer key);
Client bpSelect(Integer company_id);
}