package jp.co.ccube.ss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.co.ccube.ss.entity.Entrusted;
import jp.co.ccube.ss.entity.EntrustedExample;
import jp.co.ccube.ss.entity.EntrustedKey;

@Mapper
public interface EntrustedDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    int countByExample(EntrustedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    int deleteByExample(EntrustedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    int deleteByPrimaryKey(EntrustedKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    int insert(Entrusted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    int insertSelective(Entrusted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    List<Entrusted> selectByExample(EntrustedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    Entrusted selectByPrimaryKey(Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    int updateByExampleSelective(@Param("record") Entrusted record, @Param("example") EntrustedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    int updateByExample(@Param("record") Entrusted record, @Param("example") EntrustedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    int updateByPrimaryKeySelective(Entrusted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrusted
     *
     * @mbggenerated Tue Jul 31 13:17:23 JST 2018
     */
    int updateByPrimaryKey(Entrusted record);
}