package jp.co.ccube.ss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import jp.co.ccube.ss.entity.MClassification;
import jp.co.ccube.ss.entity.MClassificationExample;

public interface MClassificationDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	int countByExample(MClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	int deleteByExample(MClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	int deleteByPrimaryKey(String key, Integer ey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	int insert(MClassification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	int insertSelective(MClassification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	List<MClassification> selectByExample(MClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	MClassification selectByPrimaryKey(String key, Integer ey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	int updateByExampleSelective(@Param("record") MClassification record,
			@Param("example") MClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	int updateByExample(@Param("record") MClassification record, @Param("example") MClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	int updateByPrimaryKeySelective(MClassification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table m_classification
	 *
	 * @mbggenerated Wed Aug 22 16:52:44 JST 2018
	 */
	int updateByPrimaryKey(MClassification record);

	List<MClassification> selectByMClassification(MClassification recprd);

	void deleteClassification(MClassification record);
}