package jp.co.ccube.ss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.co.ccube.ss.entity.Session;
import jp.co.ccube.ss.entity.SessionExample;

@Mapper
public interface SessionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    int countByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    int deleteByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    int deleteByPrimaryKey(String jsessionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    int insert(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    int insertSelective(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    List<Session> selectByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    Session selectByPrimaryKey(String jsessionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    int updateByExampleSelective(@Param("record") Session record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    int updateByExample(@Param("record") Session record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    int updateByPrimaryKeySelective(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbggenerated Wed May 02 17:05:35 JST 2018
     */
    int updateByPrimaryKey(Session record);

    int deleteByAccountId(String accountId);
}