package jp.co.ccube.ss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.co.ccube.ss.entity.Users;
import jp.co.ccube.ss.entity.UsersExample;

@Mapper
public interface UsersDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	int countByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	int deleteByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	int deleteByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	int insert(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	int insertSelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	List<Users> selectByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	Users selectByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	int updateByPrimaryKeySelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Wed May 02 17:05:35 JST 2018
	 */
	int updateByPrimaryKey(Users record);

	Users selectByAccountId(@Param("accountId") String accountId);

	Integer countByPrimaryKey(String accountId);

	List<Users> selectByUsers(Users recprd);

	void deletedAtUpdate(String accountId);
}